name: Run Minecraft Bot with Ollama

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install ollama requests

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Git
        run: |
          sudo apt-get update
          sudo apt-get install -y git

      - name: Install Node dependencies
        run: |
          npm install
          npm install commander --save-dev
          npm install mineflayer mineflayer-pathfinder mineflayer-collectblock --save

      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh  | sh

      - name: Start Ollama Server in Background
        run: |
          nohup ollama serve > ollama.log 2>&1 &
          sleep 10

      - name: Pull Llama3 Model
        run: |
          ollama pull llama3

      - name: Run Bot Executor
        env:
          MINECRAFT_COMMAND: "Domar um cavalo"
        run: |
          python src/bot_executor.py
